apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      deployment: webapp
  replicas: 3
  template:
    metadata:
      labels:
        deployment: webapp
    spec:
      restartPolicy: Always
      containers:
      - name: webapp
        imagePullPolicy: Always
        image: webapp
        command: ["java", "-jar", "helloworld.jar"]
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "200m"
